//
//  The_SimpsonsApp.swift
//  The Simpsons
//
//  Created by Furkan Tümay on 11/25/23.
//
// UYGULAMA ICERISINDEKI GORSELLERIN TAMAMINI INTERNET UZERINDEKI CESITLI WEBSITELERINDEN ALMIS BULUNMAKTAYIM VE KESINLIKLE TICARI BIR AMAC GUTMEKSIZIN SADECE KENDIME BIR SWIFTUI ANTREMANI VE FAYDALANMAK ISTEYENLER ICINDE GUZEL BIR KODLAMA ANTREMANI OLDUGUNU DUSUNDUGUM ICIN UYGULAMA ICERISINDE YER VERMEKTEYIM. HERHANGI BIR CIZERIN OZENEREK YAPTIGI BIR EMEGI KOPYALAMA YADA COGALTMA NIYETINDE OLMADIGIMI BELIRTIRIM. ILETISIM ICIN;
// https://www.foaltycoder.co/support
// UZERINDEN BANA DILEDIGINIZ ZAMAN ULASABILIRSINIZ.

//-------------------------

// I HAVE TAKEN ALL OF THE IMAGES IN THE APPLICATION FROM VARIOUS WEBSITES ON THE INTERNET AND WITHOUT ANY COMMERCIAL PURPOSE, I AM ONLY INCLUDING THEM IN THE APPLICATION BECAUSE I THINK IT IS A SWIFTUI TRAINING FOR MYSELF AND A GOOD CODING TRAINING FOR THOSE WHO WANT TO BENEFIT FROM IT. I STATE THAT I DO NOT INTEND TO COPY OR REPRODUCE AN EFFORT MADE BY ANY ILLUSTRATOR. FOR CONTACT;
// https://www.foaltycoder.co/support
// YOU CAN REACH ME AT ANY TIME VIA

import SwiftUI

@main
struct TheSimpsonsApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
